name: Draw ZMK keymaps

on:
  workflow_dispatch:  
  push:
    paths:
      - "config/crosses.keymap"
      - "keymap_drawer.config.yaml"
      - "keymap_drawer.shortcuts.yaml"
      - ".github/workflows/draw-keymaps.yml"

jobs:
  draw:
    
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write  
    with:
      keymap_patterns: "config/crosses.keymap"
      output_folder: "img"  
      config_path: "keymap_drawer.config.yaml"
      parse_args: "crosses:'-b keymap_drawer.shortcuts.yaml --virtual-layers QWERTY-Shortcuts'"
      install_version: "0.20.0"
